# Тестовое задание

# Развернуть 2 контейнера через docker-compose.

# Первый должен быль доступен снаружи на порту 8888 установлен nginx, который перенаправляет все запросы на второй контейнер по внутренней сети docker логи необходимо писать в файловую систему хоста.

# Второй недоступен снаружи, принимает соединения только из внутренней сети на 80 порту весит веб-страничка index.php, которая выводит phpinfo(); нужно, чтобы в index.php перед вызовом функции phpinfo(); выводился IP, с которого пришел запрос Написать скрипт на bash, который при запуске будет парсить лог nginx из первого контейнера и сохранять в файл только уникальные ip адреса с которых заходили на страничкуКод скрипта и docker-compose разместить в публичном доступе github.


version: '3.3'
services:

  phpfpm:
    image: php:7-fpm
    environment:
      - CONTAINER=PROD
    networks:
      - back
    restart: always
    working_dir: /var/www/local/
    entrypoint:
      - /bin/bash
      - '-c'
      - |
        /bin/sh <<EOF
        mkdir -p /var/www/local/
        cat << EOM >/var/www/local/index.php
        <?php 
          echo %%_SERVER['REMOTE_ADDR']; 
          phpinfo();
        EOM
        sed -i 's/%%/$$/g' /var/www/local/index.php
        php-fpm
        EOF


  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - /tmp/log_container:/var/log/nginx/
    environment:
      - CONTAINER=PROD
    networks:
      - back
    restart: always
    depends_on:
      - phpfpm
    entrypoint:
      - /bin/bash
      - '-c'
      - |
        /bin/sh <<EOF 
        mkdir -p /var/www/local/
        cat << EOM >/etc/nginx/conf.d/default.conf

        server {
                  
                  listen       80;
                  server_name  _;
                  root   /var/www/local;
                  index  index.php;
                  charset utf-8;
                  error_log  /var/log/nginx/error.log;
                  access_log /var/log/nginx/access.log;
                  

                  location ~ \.php$$ {     
                        fastcgi_pass   phpfpm:9000;
                        fastcgi_index  index.php;
                        fastcgi_param  SCRIPT_NAME %%fastcgi_script_name;
                        fastcgi_param  SCRIPT_FILENAME %%document_root%%fastcgi_script_name;
                        include        fastcgi_params;
                  }

                }

                
        EOM
        cat << EON >/var/www/local/index.php
        <?php 
          echo %%_SERVER['REMOTE_ADDR'];
          phpinfo();
        EON
        sed -i 's/%%/$$/g' /etc/nginx/conf.d/default.conf
        sed -i 's/%%/$$/g' /var/www/local/index.php
        nginx -g 'daemon off;' 
        EOF



networks:
  back:
    driver: bridge